<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- robot geometric characteristics -->
    <xacro:property name="rvr_body_length" value="0.165"/>
    <xacro:property name="rvr_body_width" value="0.13"/>
    <xacro:property name="rvr_body_height" value="0.048"/>

    <xacro:property name="rvr_wheel_width" value="0.03"/>
    <xacro:property name="rvr_wheel_diameter" value="0.065"/>
    <xacro:property name="rvr_wheel_radius" value="${rvr_wheel_diameter/2}"/>

    <xacro:property name="rvr_track_dz" value="-0.008"/>
    <xacro:property name="rvr_track_length" value="0.115"/>
    <xacro:property name="rvr_track_link_size" value="0.002"/>

</robot>
