<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="track_robot">

    <!--common-->
    <xacro:include filename="$(find sphero_rvr_description)/urdf/common.urdf.xacro" />
    <xacro:include filename="$(find sphero_rvr_description)/urdf/materials.urdf.xacro" />
    <xacro:include filename="$(find sphero_rvr_description)/urdf/geometry.urdf.xacro" />

    <!-- parts -->
    <xacro:include filename="$(find sphero_rvr_description)/urdf/body.urdf.xacro" />
    <xacro:include filename="$(find sphero_rvr_description)/urdf/track.urdf.xacro" />

    <!-- urg laser -->
    <xacro:include filename="$(find urg_node)/urdf/hokuyo_ust10.urdf.xacro" />


    <!-- dummy base link no inertia to satisfy kdl -->
    <link name="base_link"/>

    <!-- Base footprint is on the ground under the robot -->
    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${-rvr_body_height/2 - 0.01}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="base_footprint" />
    </joint>

    <!-- attach body to base_link -->
    <joint name="body_inertia" type="fixed">
        <parent link="base_link" />
        <child link="body" />
    </joint>

    <!-- body acting as base link inertia -->
    <xacro:body name="body" />

    <!-- tracks -->
    <xacro:track name="left_track" parent="base_link" length="${rvr_track_length}" spin="1" >
        <origin xyz="0 ${rvr_body_width/2} ${rvr_track_dz}" rpy="0 0 0" />
    </xacro:track>

    <xacro:track name="right_track" parent="base_link" length="${rvr_track_length}" spin="-1" >
        <origin xyz="0 -${rvr_body_width/2} ${rvr_track_dz}" rpy="${M_PI} 0 0" />
    </xacro:track>

    <!-- brain -->
    <link name="pi_sbc" >
        <origin xyz="0 0 0" rpy="0 0 0" />
        <visual>
            <geometry>
                <box size="0.075 0.055 0.01" />
            </geometry>
            <material name="Green"/>
        </visual>
    </link>

    <joint name="pi_sbc_joint" type="fixed" >
        <parent link="base_link" />
        <child link="pi_sbc" />
        <origin xyz="-0.04 0 ${rvr_body_height/2 + 0.012}" rpy="0 0 0" />
    </joint>

    <!-- laser -->
    <xacro:hokuyo_ust10_mount parent_link="base_link" prefix="urg" topic="scan" >
        <origin xyz="${0.04} 0 ${rvr_body_height/2 + 0.002}" rpy="0 0 0" />
    </xacro:hokuyo_ust10_mount>

    <!-- gazebo extras -->
    <!-- gazebo control -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/</robotNamespace>
        </plugin>
    </gazebo>

    <!-- imu -->
    <gazebo>
        <plugin name="imu_controller" filename="libhector_gazebo_ros_imu.so">
        <robotNamespace>/</robotNamespace>
        <updateRate>50.0</updateRate>
        <bodyName>base_link</bodyName>
        <topicName>imu/data</topicName>
        <accelDrift>0.005 0.005 0.005</accelDrift>
        <accelGaussianNoise>0.005 0.005 0.005</accelGaussianNoise>
        <rateDrift>0.005 0.005 0.005 </rateDrift>
        <rateGaussianNoise>0.005 0.005 0.005 </rateGaussianNoise>
        <headingDrift>0.005</headingDrift>
        <headingGaussianNoise>0.005</headingGaussianNoise>
        </plugin>
    </gazebo>
</robot>
