<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="track" params="name parent *origin length spin">

        <xacro:include filename="$(find sphero_rvr_description)/urdf/geometry.urdf.xacro" />

        <xacro:include filename="$(find sphero_rvr_description)/urdf/wheel.urdf.xacro" />

        <joint name="${name}_joint" type="fixed" >
            <parent link="${parent}" />
            <child link="${name}" />
            <xacro:insert_block name="origin" />
        </joint>

        <link name="${name}" >
            <visual>
                <geometry>
                    <box size="${length} ${rvr_track_link_size} ${rvr_track_link_size}" />
                </geometry>
                <material name="LightGrey"/>
            </visual>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="0.01" />
                <inertia
                    ixx="${0.001}" ixy="0.0" ixz="0.0"
                    iyy="${0.001}" iyz="0.0"
                    izz="${0.001}"/>
            </inertial>
        </link>

        <xacro:wheel name="${name}_back_wheel" parent="${name}" direction="${spin}" >
            <origin xyz="-${length/2} ${rvr_track_link_size/2} 0" rpy="0 0 0" />
        </xacro:wheel>

        <xacro:wheel name="${name}_front_wheel" parent="${name}" direction="${spin}">
            <origin xyz="${length/2} ${rvr_track_link_size/2} 0" rpy="0 0 0" />
        </xacro:wheel>

    </xacro:macro>

</robot>
